### ISSUE TITLE
Duplicated CXXFLAGS in Makefile

### ISSUE THREAD

**Issue by BlaCkinkGJ** [fmowl10/snake-clone#2]
I found some duplicated CXXFLAGS in Makefile. Is there any reason to keep it duplicated?

https://github.com/fmowl10/snake-clone/blob/3b67fef52e0942e9938dfa6839b3f9f25c3feb3e/Makefile#L28

**Comment by BlaCkinkGJ** [comment]
I also found that `Makefile` does not have `--std=c++11` option. It will have problems on other platforms if it does not have this flag.

**Comment by fmowl10** [comment]
> I found some duplicated CXXFLAGS in Makefile. Is there any reason to keep it duplicated?
> 
> https://github.com/fmowl10/snake-clone/blob/3b67fef52e0942e9938dfa6839b3f9f25c3feb3e/Makefile#L28

`Makefile` was replaced with `meson.build`. It will be remove in the next version or commit. and more directories and files will be removed. this is list.

- [x] `Makefile`

- [x] `report`

**Comment by fmowl10** [comment]
> I also found that `Makefile` does not have `--std=c++11` option. It will have problems on other platforms if it does not have this flag.

thanks your advice. that option will be add in `meson.build`.
